name: Deploy

on: 
  push:
    branches:
      - main

env: 
  SERVER_HOST: 185.209.115.227 
  SERVER_USER: root
  SERVER_PATH: /root/github-test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Install SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.MY_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Generate auth token
        run: ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts 
      - name: Deploy
        run: rsync --archive --compress --progress . ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH }}
          
